[package]
name = "blocks-cs-sort"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rayon = "1.8"

[dev-dependencies]
proptest = "1.4"
criterion = "0.5"
